DontShowPostsBefore: 2016-08-01t01:00:00:00-08:00

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Campus Gamers at Bakersfield College (BC Renegamers)
email: bcrenegamers@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" 
url: "https://renegamers.github.io"

# Build settings
 encoding: "UTF-8"
 lang: "en-US"
 timezone: "America/Los_Angeles"
 lsi: false
 permalink: /:year/:month/:day/:title.html
 future: true
 sass:
   style: compressed
 gems:
  - jekyll-sass-converter
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
 defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "minutes"
      title: "Minutes"
  -
    scope:
      path: "_posts/agenda"
      type: "posts"
    values:
      layout: "agenda"
      title: "Agenda"

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - readme.md
  - script
  - vendor
